data = [
    {"name": "China", "population (millions)": 1441, "language": "Mandarin", "continent": "Asia"},
    {"name": "India", "population (millions)": 1412, "language": "Hindi", "continent": "Asia"},
    {"name": "United States", "population (millions)": 331, "language": "English", "continent": "North America"},
    {"name": "Indonesia", "population (millions)": 276, "language": "Indonesian", "continent": "Asia"},
    {"name": "Pakistan", "population (millions)": 240, "language": "Urdu", "continent": "Asia"},
    {"name": "Brazil", "population (millions)": 214, "language": "Portuguese", "continent": "South America"},
    {"name": "Nigeria", "population (millions)": 213, "language": "English", "continent": "Africa"},
    {"name": "Bangladesh", "population (millions)": 171, "language": "Bengali", "continent": "Asia"},
    {"name": "Russia", "population (millions)": 145, "language": "Russian", "continent": "Europe/Asia"},
    {"name": "Mexico", "population (millions)": 128, "language": "Spanish", "continent": "North America"},
    {"name": "Japan", "population (millions)": 125, "language": "Japanese", "continent": "Asia"},
    {"name": "Ethiopia", "population (millions)": 123, "language": "Amharic", "continent": "Africa"},
    {"name": "Philippines", "population (millions)": 113, "language": "Filipino", "continent": "Asia"},
    {"name": "Egypt", "population (millions)": 110, "language": "Arabic", "continent": "Africa"},
    {"name": "Vietnam", "population (millions)": 98, "language": "Vietnamese", "continent": "Asia"},
    {"name": "DR Congo", "population (millions)": 95, "language": "French", "continent": "Africa"},
    {"name": "Turkey", "population (millions)": 86, "language": "Turkish", "continent": "Asia/Europe"},
    {"name": "Iran", "population (millions)": 86, "language": "Persian", "continent": "Asia"},
    {"name": "Germany", "population (millions)": 83, "language": "German", "continent": "Europe"},
    {"name": "Thailand", "population (millions)": 71, "language": "Thai", "continent": "Asia"},
    {"name": "United Kingdom", "population (millions)": 67, "language": "English", "continent": "Europe"},
    {"name": "France", "population (millions)": 65, "language": "French", "continent": "Europe"},
    {"name": "Italy", "population (millions)": 59, "language": "Italian", "continent": "Europe"},
    {"name": "Tanzania", "population (millions)": 63, "language": "Swahili", "continent": "Africa"},
    {"name": "South Africa", "population (millions)": 60, "language": "Zulu", "continent": "Africa"},
    {"name": "Myanmar", "population (millions)": 55, "language": "Burmese", "continent": "Asia"},
    {"name": "South Korea", "population (millions)": 52, "language": "Korean", "continent": "Asia"},
    {"name": "Colombia", "population (millions)": 52, "language": "Spanish", "continent": "South America"},
    {"name": "Kenya", "population (millions)": 55, "language": "Swahili", "continent": "Africa"},
    {"name": "Spain", "population (millions)": 48, "language": "Spanish", "continent": "Europe"},
    {"name": "Argentina", "population (millions)": 46, "language": "Spanish", "continent": "South America"},
    {"name": "Ukraine", "population (millions)": 36, "language": "Ukrainian", "continent": "Europe"},
    {"name": "Iraq", "population (millions)": 44, "language": "Arabic", "continent": "Asia"},
    {"name": "Sudan", "population (millions)": 45, "language": "Arabic", "continent": "Africa"},
    {"name": "Algeria", "population (millions)": 45, "language": "Arabic", "continent": "Africa"},
    {"name": "Uganda", "population (millions)": 47, "language": "English", "continent": "Africa"},
    {"name": "Poland", "population (millions)": 38, "language": "Polish", "continent": "Europe"},
    {"name": "Canada", "population (millions)": 38, "language": "English/French", "continent": "North America"},
    {"name": "Morocco", "population (millions)": 37, "language": "Arabic", "continent": "Africa"},
    {"name": "Saudi Arabia", "population (millions)": 36, "language": "Arabic", "continent": "Asia"},
    {"name": "Uzbekistan", "population (millions)": 35, "language": "Uzbek", "continent": "Asia"},
    {"name": "Peru", "population (millions)": 34, "language": "Spanish", "continent": "South America"},
    {"name": "Malaysia", "population (millions)": 33, "language": "Malay", "continent": "Asia"},
    {"name": "Afghanistan", "population (millions)": 41, "language": "Pashto/Dari", "continent": "Asia"},
    {"name": "Venezuela", "population (millions)": 33, "language": "Spanish", "continent": "South America"},
    {"name": "Angola", "population (millions)": 36, "language": "Portuguese", "continent": "Africa"},
    {"name": "Nepal", "population (millions)": 30, "language": "Nepali", "continent": "Asia"},
    {"name": "Ghana", "population (millions)": 34, "language": "English", "continent": "Africa"},
    {"name": "Yemen", "population (millions)": 34, "language": "Arabic", "continent": "Asia"},
    {"name": "Mozambique", "population (millions)": 33, "language": "Portuguese", "continent": "Africa"}
]
